### PR TITLE
Add LCD and LCD backlight support to tmk_core

### PR DESCRIPTION
**Pull request by fredizzimo**
This will just add support to the tmk_core library. The uGFX library is added as a submodule, which is used for controlling the LCD.

All the interesting stuff is in the Ergodox Infinity project. I will open a pull request for that later, when this one is merged, and I'm able to update the submodule to point to the right repository and branch.

There are quite many commits, so if you want, I could create another pull request with some of the commits merged. Or even with everything as one single commit.

I have also removed some warnings, do you want those separated as a separate pull request?

### CODE REVIEW

**Comment by tmk** [comment]
Interesting feature, but I hesitate to integrate it to tmk_core, I think keyboard specific feature should be maintained inside keyboard project repository.

I think we need rather generic purpose interface to execute user code before or inside main loop and when interesting events occur. Unfortunately tmk_core doesn't have good interface for this purpose.

In this case,
1) you need to initialize your peripherals at startup and
https://github.com/tmk/tmk_core/pull/2/files#diff-1bf1c9f8a61dd545315b8172116a190dR125

2) you are interested in watching change of layer and LED state in main loop.
https://github.com/tmk/tmk_core/pull/2/files#diff-1bf1c9f8a61dd545315b8172116a190dR140

How about adding two API `keyboard_init()` and `keyboard_loop()` so that user can insert their code?

```
main() {
    keyboard_init();
    while (true) {
        ...
        keyboard_loop();
        ...
    }
}
```

**Comment by fredizzimo** [comment]
Hi TMK,

I definitely understand your concern, and that's why I only included a minimal interface on the core side, rather than the actual implementation at this stage. Your proposed interface would definitely work, and I can change my code to use that instead if you wanted.

However from my point of view, at least the visualization concept is generic, and could apply to any keyboard. Not  many keyboards out there today allows as much customization as the Ergodox Infinity though. 

Likewise, although no keyboards have an LCD with backlight, that's something we could definitely see in the future, at least for the future Infinity keyboards. I can even see touch screens being added at some point.

That's why I made the interface so that the visualization code could be a part of the core library. I think as it's written now in my Ergodox repository, it would work generically for all chibios platforms, if moved into the core library. The visualizer really doesn't need the LCD screen or backlight and compiles with both of those disabled currently. If support was added for normal key leds, it would work for them as well. 

Some parts of the visualization code, like the generic animation support, is definitely complex and generic enough to warrant it's own library. The led code also has some code for calculating RGB values from Hue, Saturation and Intensity, which is also quite complex. So if including those in the core library in the future wouldn't be an option, then maybe rather than having this as a part of core, there could be some kind of visualization library that could be shared?

But then comes the question of what to do with similar features? There are already backlight and normal keyboard led(caps lock, num lock and so on) support. Those should probably be part of the same library, and be something that the visualizer could control.

Finally, there's a problem that I didn't encounter yet, but probably will in the future. We need support for LED contrast, and LCD backlight brightness adjustments. The most logical place for persisting that would be in the eeprom. But that part of the code is in the core library, do you have any suggestions on how to integrate that if it was part of the user code? 

It's probably also not a good idea, to continue to use ifdefs like you use for existing backlight values, as the location will move around, depedning on which features you have enabled, and things could get messed up if you disable or enable something temporarily. So it would probably be better to always write the values for the few things we need, at the potential cost of reduced eeprom lifetime of course.

Another thing that would be needed if we go with the generic interface that you proposed, is some interface for the suspend/wakup. Currently my code doesn't handle the keyboard going to sleep, but it probably should, by allowing the user to chose if there should be some kind of animation, or more likely to shut the LCD off completely during the sleep.

Best Regards,
Fred Sundvik

**Comment by tmk** [comment]
I think visualization is not requisite feature for keyboard and not specific to it so it won't be integrated and independent visualization library/code would be useful. For example, I can use the library when adding LCD to my toaster reflow oven instead of keyboard.

And I've been going to remove **blacklight support** from tmk_core and add some API for general use instead. Lock key **LED indicator** supoport will stay in tmk_core but it will be changed a bit.
https://github.com/tmk/tmk_keyboard/issues/174

As for eeprom we need more generic API instead of `eeconfig.h` too.

I filed issue for this. https://github.com/tmk/tmk_keyboard/issues/304

**Comment by fredizzimo** [comment]
Ok. I will refactor my code to use the API that you suggested, including adding the API functions to the core library (but only called when chibios is enabled, as I can't test the other variations). Do you have any preference of in which header file the two API functions should be declared? I think it's better and faster that I add them, because I can verify that they are good enough for what I need at the same time.

The I will also have to include the change that I did to https://github.com/tmk/tmk_core/pull/1, which I closed earlier, so I can add new header directories, for the uGFX lib for example, but also for the library part of the Visualizer. 

I also started to wonder, since I already made some big changes to the Infinity Ergodox project, and will add more when I get the UART support done, do you think it would make sense that I took over the maintenance of that project completely, to save you from some work? Otherwise I doubt that those two things would be the only pull requests that I would send.

**Pull request closed without merging**
